#——————————————————————————————————————————————————————————
#                          语言配置
#——————————————————————————————————————————————————————————
没物品消息: "你没有足够的物品"
背包满消息: "背包已满，多购部分已退回"
操作失败消息: "操作失败"
没有页数消息: "没有第%页数%页哦！"
手续费不足: "你没有足够的钱作为本次交易的手续费，需要%钱%元"
扣除手续费: "本次交易收取手续费%钱%元"
增加手续费: "本次消费需要手续费%钱%元，已算入总消费。"
#——————————————————————————————————————————————————————————
#                          商品配置
#——————————————————————————————————————————————————————————
#涨跌指数达到+-涨跌指数时回调整物品价格
涨跌价格: 0.1
#涨跌指数越低，调整价格越频繁，（涨跌指数就是玩家购买物品量）
#涨跌指数高于或低于此值时会开始调整物品价格
涨跌指数: 10
#最高价格，与最低价格
默认价格: 10
全局最高价格: 500
全局最低价格: 0.0001
#购买和出售都扣除手续费，填任意负数关闭
手续费: -1
#——————————————————————————————————————————————————————————
#                          自定义配置
#——————————————————————————————————————————————————————————
箱子标题: "§d§l市场  第%页数%页"
上一页按钮名字: "§a§l上一页"
上一页物品按钮: "MAGENTA_STAINED_GLASS_PANE"
下一页按钮名字: "§a§l下一页"
下一页物品按钮: "MAGENTA_STAINED_GLASS_PANE"
无商品名字: "§7§l此处无商品"
无商品显示物品: "LIGHT_GRAY_STAINED_GLASS_PANE"
错误物品: "BEDROCK"
价格显示:
  - "§f-------------------------------"
  - "§d物品价格：§e%价格%  §a|  §d跌涨指数：§e%购买数量%"
  - "§d服务器账户余额：§e%服务器账户余额%"
  - "§f-------------------------------"
  - "§e左键购买，右键出售"
  - "§eShift+左键/右键，购买/出售一组"
  - "§f-------------------------------"
